# Generated by Django 3.0.4 on 2020-03-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='description',
            field=models.TextField(default='description default text'),
        ),
    ]
