# Generated by Django 3.0.4 on 2020-03-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profiles_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='job',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
