# Generated by Django 3.0.4 on 2020-03-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profiles_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='location',
            field=models.CharField(blank=True, default='my location default', max_length=120, null=True),
        ),
    ]
