# Generated by Django 3.0.4 on 2020-03-09 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200309_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='job',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='location',
        ),
    ]
